Repository berty/yolo, pull requests merged in 2020-04, with the labels that each got.

#152 Fix(front): Fit build card contents onto small screen
  web/src/ui/components/BuildCard/BuildCard.scss
Labels: 🔍 Ready for Review

#154 fix: move everything go in go/
  .circleci/config.yml
  .github/CODEOWNERS
  .github/SECURITY.md
  CODE_OF_CONDUCT.md
  Dockerfile
  Makefile
  README.md
  api/yolopb.proto
  doc.go
  gen.sum
  go/.golangci.yml
  go/Makefile
  go/cmd/yolo/main.go
  go/gen.sum
  go/pkg/bintray/bintray.go
  go/pkg/bintray/types.go
  go/pkg/plistgen/plistgen.go
  go/pkg/testutil/doc.go
  go/pkg/testutil/golden.go
  go/pkg/testutil/logging.go
  go/pkg/yolopb/batch.go
  go/pkg/yolopb/model.go
  go/pkg/yolopb/types.go
  go/pkg/yolopb/yolopb.pb.go
  go/pkg/yolopb/yolopb.pb.gw.go
  go/pkg/yolosvc/api_buildlist.go
  go/pkg/yolosvc/api_buildlistfilters.go
  go/pkg/yolosvc/api_dev.go
  go/pkg/yolosvc/api_download.go
  go/pkg/yolosvc/api_ping.go
  go/pkg/yolosvc/api_plist.go
  go/pkg/yolosvc/api_status.go
  go/pkg/yolosvc/cache.go
  go/pkg/yolosvc/db.go
  go/pkg/yolosvc/driver_bintray.go
  go/pkg/yolosvc/driver_buildkite.go
  go/pkg/yolosvc/driver_circleci.go
  go/pkg/yolosvc/driver_github.go
  go/pkg/yolosvc/server.go
  go/pkg/yolosvc/service.go
  go/pkg/yolosvc/util.go
  pkg/bintray/doc.go
  pkg/plistgen/doc.go
  pkg/yolopb/doc.go
  pkg/yolosvc/doc.go
Labels: 🔍 Ready for Review

#155 fix: No race condition on landing default param push
  web/src/ui/pages/Home/Home.js
Labels: ✅ Approved

#157 Fix(front): Improve some API and UI response mapping
  web/src/ui/components/BuildCard/ArtifactCard.js
  web/src/ui/components/BuildCard/BuildCard.js
  web/src/ui/components/BuildCard/BuildCard.scss
Labels: front, 🔍 Ready for Review

#158 feat: 'yolo dump-objects' cli
  go/cmd/yolo/main.go
  go/pkg/yolosvc/api_dev.go
Labels: 🔍 Ready for Review
