Repository berty/yolo, pull requests merged in 2020-09, with the labels that each got.

#379 feat(web): hide full feed by default
  web/src/ui/components/Build/BuildBlockHeader.js
  web/src/ui/components/BuildList.js
Labels: enhancement, front, 🔍 Ready for Review

#380 fix(front): show feed button margin
  web/src/ui/components/BuildList.js
Labels: bug, front, front-cosmetic, 🔍 Ready for Review

#381 feat(front): improve artifact download button
  web/.eslintrc.json
  web/src/ui/components/Build/ArtifactRow.js
  web/src/ui/components/Build/Build.module.scss
  web/src/ui/components/BuildList.js
  web/src/ui/styleTools/themes.js
Labels: enhancement, front, front-cosmetic, 🔍 Ready for Review

#382 fix(front): minor ui improvements
  web/src/ui/components/Build/ArtifactRow.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/Filters/Filters.js
Labels: bug, front, 🔍 Ready for Review

#384 feat(deployment): add traefik labels to compose
  deployments/yolo.berty.io/docker-compose.yml
Labels: enhancement, ✅ Approved

#385 feat: github actions driver
  go.mod
  go.sum
  go/cmd/yolo/main.go
  go/pkg/yolosvc/api_download.go
  go/pkg/yolosvc/db.go
  go/pkg/yolosvc/driver_bintray.go
  go/pkg/yolosvc/driver_buildkite.go
  go/pkg/yolosvc/driver_circleci.go
  go/pkg/yolosvc/driver_github.go
  go/pkg/yolosvc/driver_pkgman.go
  go/pkg/yolosvc/service.go
Labels: enhancement, 🔍 Ready for Review

#387 feat: extract some metadata from the .apk files
  go.mod
  go.sum
  go/pkg/yolosvc/driver_pkgman.go
Labels: enhancement, 🔍 Ready for Review

#388 feat: Store Theme in localStorage.
  web/src/store/ThemeStore.js
Labels: enhancement, ✅ Approved
