Repository berty/yolo, pull requests merged in 2020-11, with the labels that each got.

#415 fix: bump bearer agent
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review

#416 feat: add log filters support
  go.mod
  go.sum
  go/cmd/yolo/main.go
Labels: enhancement, 🔍 Ready for Review

#417 chore: sync infra config
  deployments/yolo.berty.io/docker-compose.yml
Labels: chore, 🔍 Ready for Review
