Repository berty/yolo, pull requests merged in 2020-10, with the labels that each got.

#391 chore: update README logo (fix #150)
  README.md
Labels: chore, 🔍 Ready for Review

#389 feat: sign unsigned iOS apps (.app) into .ipa
  .gitignore
  Dockerfile
  deployments/yolo.berty.io/.env.example
  deployments/yolo.berty.io/docker-compose.yml
  go.mod
  go.sum
  go/cmd/yolo/main.go
  go/pkg/yolosvc/api_download.go
  go/pkg/yolosvc/service.go
  go/pkg/yolosvc/util.go
Labels: enhancement, 🔍 Ready for Review

#392 feat: advanced artifact caching
  go/pkg/yolosvc/api_artifactgetfile.go
  go/pkg/yolosvc/api_artifacticon.go
  go/pkg/yolosvc/api_download.go
  go/pkg/yolosvc/driver_pkgman.go
  go/pkg/yolosvc/service.go
  go/pkg/yolosvc/util.go
Labels: enhancement, 🔍 Ready for Review

#393 chore: set default value to github action instead of buildkite
  web/src/constants/index.js
Labels: chore, 🔍 Ready for Review

#390 feat: Save last filters as next default filters.
  web/src/hooks/queryHooks.js
  web/src/store/GlobalStore.js
  web/src/ui/components/FilterModal/FilterModal.js
Labels: WIP, enhancement, ✅ Approved

#394 chore: update default options
  web/src/constants/index.js
  web/src/hooks/queryHooks.js
  web/src/store/GlobalStore.js
  web/src/store/ThemeStore.js
  web/src/store/globalStoreHelpers.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/FilterModal/FilterModalWidgets.js
Labels: chore, 🔍 Ready for Review

#395 chore: support various IPAs app icon sizes
  go/pkg/yolosvc/driver_pkgman.go
Labels: chore, 🔍 Ready for Review

#396 chore: support apps without display name
  go/pkg/yolosvc/driver_pkgman.go
Labels: chore, 🔍 Ready for Review

#397 feat: add a new routine that tries to fix orphans
  go/pkg/yolosvc/driver_github.go
  go/pkg/yolosvc/server.go
Labels: enhancement, 🔍 Ready for Review

#398 chore: add basic pagination on github driver
  go/pkg/yolosvc/db.go
  go/pkg/yolosvc/driver_github.go
Labels: chore, 🔍 Ready for Review

#399 feat: add ?with_no_mergerequet and disable builds without merge request by default
  api/yolopb.proto
  go/gen.sum
  go/pkg/yolopb/yolopb.pb.go
  go/pkg/yolosvc/api_buildlist.go
Labels: enhancement, 🔍 Ready for Review

#400 chore: bump go1.15
  .github/workflows/ci.yml
  Dockerfile
Labels: chore, 🔍 Ready for Review

#401 fix(github): use head repo to get the belonging PR
  go/pkg/yolosvc/driver_github.go
Labels: bug, 🔍 Ready for Review

#402 build(front): bump web deps
  web/package-lock.json
  web/package.json
Labels: build, front, 🔍 Ready for Review

#403 feat(js): scroll-to behavior when showing/hiding feed
  web/.babelrc
  web/package-lock.json
  web/package.json
  web/src/ui/components/BuildList.js
  web/src/util/misc.js
Labels: enhancement, front, 🔍 Ready for Review

#404 feat(js): add Download and QR Popup buttons to collapsed build blocks
  web/src/assets/svg/yolo-logo-square.svg
  web/src/ui/components/Build/ArtifactRow.js
  web/src/ui/components/Build/BuildBlockHeader.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/MessageModal/MessageModal.js
  web/src/ui/components/MessageModal/MessageModal.scss
  web/src/ui/components/QRCodeModal.js
  web/src/ui/pages/Home/Home.module.scss
Labels: enhancement, front, 🔍 Ready for Review

#405 fix: scroll on show feed behavior missing on some requests
  web/src/ui/components/ApiKeyPrompt.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/ErrorDisplay/ErrorDisplay.module.scss
  web/src/ui/pages/Home/Home.js
  web/src/ui/pages/Home/Home.module.scss
Labels: bug, front, 🔍 Ready for Review

#406 fix(ui): header vertical overflow
  web/src/ui/pages/Home/Home.module.scss
Labels: bug, front, 🔍 Ready for Review

#407 fix: pull to refresh
  web/src/api/index.js
  web/src/hooks/queryHooks.js
  web/src/store/GlobalStore.js
  web/src/store/globalStoreHelpers.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/Filters/Filters.js
  web/src/ui/components/MessageModal/MessageModal.scss
  web/src/ui/components/ProtocolDisclaimer.js
  web/src/ui/components/PullToRefresh.js
  web/src/ui/pages/Home/Home.js
  web/src/ui/pages/Home/Home.module.scss
Labels: bug, front, 🔍 Ready for Review

#408 feat(front): easier-to-press feed display toggler
  web/src/ui/components/BuildList.js
Labels: enhancement, front, 🔍 Ready for Review

#409 fix(ui): collapsed block download btn click event propagates
  web/src/ui/components/Build/BuildContainer.js
Labels: bug, front, 🔍 Ready for Review

#412 fix(js): index and commit front env file
  web/.env
  web/.gitignore
Labels: bug, front, 🔍 Ready for Review

#413 fix: last build default collapse as true
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/BuildList.js
Labels: bug, ✅ Approved
