Repository berty/yolo, pull requests merged in 2020-07, with the labels that each got.

#364 chore: remove Circle CI tests
  .circleci/config.yml
Labels: chore, 🔍 Ready for Review

#365 feat(front): ui improvements
  web/src/ui/components/Author/Author.js
  web/src/ui/components/Build/BuildAndMrContainer.js
  web/src/ui/components/Build/BuildBlockHeader.js
  web/src/ui/components/Build/BuildBlockTitle.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/FilterModal/FilterModalWidgets.js
  web/src/ui/pages/Home/Home.js
  web/src/ui/styleTools/ownerIcons.js
  web/src/ui/styleTools/projectIcons.js
  web/src/wdyr.js
Labels: enhancement, 🔍 Ready for Review

#366 fix(front): autoreload bug
  web/src/store/GlobalStore.js
  web/src/ui/pages/Home/Home.js
Labels: bug, 🔍 Ready for Review

#367 feat(front): replace text with icons on mobile
  web/src/assets/img/cci_black.png
  web/src/assets/img/cci_white.png
  web/src/assets/svg/bintray_svg.svg
  web/src/assets/svg/bintray_svg_white.svg
  web/src/assets/svg/bkbw.svg
  web/src/constants/index.js
  web/src/store/GlobalStore.js
  web/src/ui/components/Filters/Filters.js
  web/src/ui/styleTools/otherIcons.js
Labels: enhancement, 🔍 Ready for Review

#371 feat(front): pull to refresh build list
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/api/apiResponseTransforms.js
  web/src/api/index.js
  web/src/hooks/queryHooks.js
  web/src/ui/components/BuildListContainer.js
  web/src/ui/components/Header/Header.module.scss
  web/src/ui/components/PullToRefresh.js
  web/src/ui/components/ShowFiltersButton.js
  web/src/ui/components/Spinner/Spinner.module.scss
  web/src/ui/pages/Home/Home.js
Labels: enhancement, front, 🔍 Ready for Review

#373 fix(front): clicking entire collapsed build block now toggles collapsed state
  web/src/ui/components/Build/ArtifactRow.js
  web/src/ui/components/Build/BuildBlockHeader.js
  web/src/ui/components/Build/BuildContainer.js
Labels: bug, front, 🔍 Ready for Review

#374 fix(front): hotfix - remove pull to refresh while debugging
  web/src/ui/pages/Home/Home.js
Labels: bug, 🔍 Ready for Review
