Repository berty/yolo, pull requests merged in 2020-05, with the labels that each got.

#160 fix: ambiguous sql query in some cases
  go/pkg/yolosvc/api_buildlist.go
Labels: 🔍 Ready for Review

#161 fix: do not send WWW-Authenticate header (fix #143)
  go/pkg/yolosvc/server.go
Labels: 🔍 Ready for Review

#162 Fix(front): Hide filters and buttons from unauthorized users
  web/src/ui/components/Header/Header.js
  web/src/ui/components/ThemeToggler.js
  web/src/ui/pages/Home/Home.js
Labels: front, 🔍 Ready for Review

#166 Feat(front): Add UI message when no results found
  web/src/ui/components/BuildList.js
Labels: 🔍 Ready for Review

#167 Add MR Title with PR id and Build ID fallbacks to card title
  web/src/ui/components/BuildCard/ArtifactCard.js
  web/src/ui/components/BuildCard/BuildCard.js
Labels: front, 🔍 Ready for Review

#165 Docs: Small philosophy statement in README
  README.md
Labels: ✅ Approved

#174 Feat(web): Small additions and fixes
  web/src/api/dataTransforms.js
  web/src/constants/index.js
  web/src/store/ResultStore.js
  web/src/ui/components/BuildCard/ArtifactCard.js
  web/src/ui/components/BuildCard/BuildCard.js
  web/src/ui/components/BuildCard/BuildCard.scss
  web/src/ui/components/BuildList.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/pages/Home/Home.js
Labels: 🔍 Ready for Review

#170 Feat(web): Collapse cards if any branch in results is master
  web/src/api/dataTransforms.js
  web/src/ui/components/BuildList.js
Labels: 🔍 Ready for Review

#175 Fix: Keep MR message as subtitle in buildcards
  web/src/ui/components/BuildCard/BuildCard.js
  web/src/ui/components/BuildCard/BuildCard.scss
Labels: 🔍 Ready for Review

#176 Feat(web): Add build, artifact, and MR driver names to build cards
  web/src/assets/_variables.scss
  web/src/ui/components/BuildCard/ArtifactCard.js
  web/src/ui/components/BuildCard/BuildCard.js
Labels: 🔍 Ready for Review

#178 Feat(web): Style and add links to tags in build cards
  web/src/constants/index.js
  web/src/ui/components/BuildCard/BuildCard.js
  web/src/ui/components/BuildCard/BuildCard.scss
  web/src/ui/styleTools/buttonStyler.js
Labels: front, 🔍 Ready for Review

#179 Feat(web): Move logout and theme toggler to filters modal
  web/src/store/ResultStore.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/FilterModal/FilterModal.scss
  web/src/ui/components/Filters/Filters.js
  web/src/ui/components/Filters/Filters.scss
  web/src/ui/components/Header/Header.js
  web/src/ui/components/ThemeToggler.js
Labels: 🔍 Ready for Review

#181 Feat(web): Add some build metadata regardless has_mergerequest
  web/src/ui/components/BuildCard/ArtifactCard.js
  web/src/ui/components/BuildCard/BuildCard.js
  web/src/ui/components/BuildCard/BuildCard.scss
  web/src/ui/styleTools/buttonStyler.js
  web/src/util/date.js
Labels: 🔍 Ready for Review

#184 Fix(front): Fix various tag alignment issues for small screens
  web/src/assets/_breakpointMixins.scss
  web/src/assets/_variables.scss
  web/src/ui/components/BuildCard/ArtifactCard.js
  web/src/ui/components/BuildCard/BuildCard.js
  web/src/ui/components/BuildCard/BuildCard.scss
Labels: front, 🔍 Ready for Review

#187 Fix(front): Manual refresh preserves URL bar query
  web/src/store/ResultStore.js
  web/src/ui/components/Filters/Filters.js
  web/src/ui/pages/Home/Home.js
Labels: 🔍 Ready for Review

#188 feat: guess missing build info
  go/pkg/yolosvc/driver_bintray.go
  go/pkg/yolosvc/driver_buildkite.go
  go/pkg/yolosvc/driver_circleci.go
  go/pkg/yolosvc/util.go
Labels: 🔍 Ready for Review

#189 feat: HTTP client caching
  go.mod
  go.sum
  go/cmd/yolo/main.go
Labels: 🔍 Ready for Review

#196 refactor(front): small cleanups in buildCard
  web/src/ui/components/BuildCard/BuildCard.js
  web/src/ui/components/BuildCard/BuildCard.scss
Labels: 🔍 Ready for Review

#197 feat(front): basic support for extra-small screens
  web/src/assets/main.scss
  web/src/ui/components/BuildCard/BuildCard.js
  web/src/ui/components/BuildCard/BuildCard.scss
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/FilterModal/FilterModal.scss
  web/src/ui/components/Filters/Filters.scss
  web/src/ui/components/Header/Header.scss
  web/src/ui/components/ShowFiltersButton.js
  web/src/ui/styleTools/buttonStyler.js
Labels: front, 🔍 Ready for Review

#198 fix: send WWW-Authenticate header when calling the API without referer
  go/pkg/yolosvc/server.go
Labels: 🔍 Ready for Review

#199 feat(front): modify and display artifact kind filters
  web/src/constants/index.js
  web/src/store/ResultStore.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/FilterModal/FilterModal.scss
  web/src/ui/components/Filters/Filters.js
  web/src/ui/pages/Home/Home.js
Labels: 🔍 Ready for Review

#200 test(front): update fetch stub
  web/package.json
  web/src/api/mock.js
Labels: 🔍 Ready for Review

#194 feat(web): format card titles with PR links
  web/src/ui/components/BuildCard/BuildCard.js
  web/src/ui/components/Header/Header.js
Labels: 🔍 Ready for Review

#205 feat(front): add anchor links to builds and artifacts
  web/package-lock.json
  web/package.json
  web/src/constants/index.js
  web/src/store/ResultStore.js
  web/src/ui/components/AnchorLink.js
  web/src/ui/components/BuildCard/ArtifactCard.js
  web/src/ui/components/BuildCard/BuildCard.js
  web/src/ui/components/BuildCard/BuildCard.scss
  web/src/ui/components/BuildList.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/ShowFiltersButton.js
  web/src/ui/pages/Home/Home.js
Labels: 🔍 Ready for Review

#206 fix(front): fix unwanted theme change on opening filter settings modal
  web/src/store/ThemeStore.js
  web/src/ui/components/FilterModal/FilterModal.scss
  web/src/ui/components/ThemeToggler.js
Labels: 🔍 Ready for Review

#207 fix(front): make protocol warning button look interactive
  web/src/ui/components/MessageModal/MessageModal.js
  web/src/ui/components/MessageModal/MessageModal.scss
Labels: front, 🔍 Ready for Review

#213 feat(web): return home on clicking logo
  web/src/ui/components/Header/Header.js
Labels: 🔍 Ready for Review

#211 feat(front): group buildlist results by pull request
  web/src/api/dataTransforms.js
  web/src/store/ResultStore.js
  web/src/ui/components/AnchorLink.js
  web/src/ui/components/Build/ArtifactCard.js
  web/src/ui/components/Build/Build.scss
  web/src/ui/components/Build/BuildAndMergeRequest.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/Build/CardHeader.js
  web/src/ui/components/Build/CardTitle.js
  web/src/ui/components/BuildCard/BuildCard.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/Header/Header.js
Labels: 🔍 Ready for Review

#214 feat: improve relationship detection for bintray driver
  api/yolopb.proto
  go/cmd/yolo/main.go
  go/gen.sum
  go/pkg/bintray/bintray.go
  go/pkg/bintray/types.go
  go/pkg/yolopb/yolopb.pb.go
  go/pkg/yolosvc/driver_bintray.go
  go/pkg/yolosvc/util.go
Labels: api, 🔍 Ready for Review

#215 feat: add more metadata in generated plist
  go/pkg/plistgen/plistgen.go
  go/pkg/yolosvc/api_plist.go
  web/src/assets/favicon/bundle-512x512.png
  web/src/assets/favicon/bundle-57x57.png
Labels: 🔍 Ready for Review

#218 feat(front): allow filtering from ui by project
  web/src/constants/index.js
  web/src/store/ResultStore.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/FilterModal/FilterModal.scss
  web/src/ui/components/Filters/Filters.js
  web/src/ui/pages/Home/Home.js
Labels: ✅ Approved

#222 build(front): configure linter
  web/.eslintignore
  web/.eslintrc.json
  web/.prettierrc
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/api/auth.js
  web/src/api/dataTransforms.js
  web/src/api/index.js
  web/src/api/mock.js
  web/src/assets/svg/IconChat.js
  web/src/assets/svg/IconMini.js
  web/src/constants/actions.js
  web/src/constants/index.js
  web/src/index.js
  web/src/store/ResultStore.js
  web/src/store/ThemeStore.js
  web/src/ui/components/ActionWidgets.js
  web/src/ui/components/AnchorLink.js
  web/src/ui/components/ApiKeyPrompt.js
  web/src/ui/components/Build/ArtifactCard.js
  web/src/ui/components/Build/BuildAndMergeRequest.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/Build/CardHeader.js
  web/src/ui/components/Build/CardTitle.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/ErrorDisplay/ErrorDisplay.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/Filters/Filters.js
  web/src/ui/components/Header/Header.js
  web/src/ui/components/MessageModal/MessageModal.js
  web/src/ui/components/ShowFiltersButton.js
  web/src/ui/components/ThemeToggler.js
  web/src/ui/pages/Error404.js
  web/src/ui/pages/Home/Home.js
  web/src/ui/styleTools/buttonStyler.js
  web/src/ui/styleTools/themes.js
  web/src/util/date.js
  web/webpack.config.dev.js
  web/webpack.config.prod.js
Labels: 🔍 Ready for Review

#225 feat(front): clicking a filter widget in header opens filter modal
  web/src/ui/components/Filters/Filters.js
  web/src/ui/components/Filters/Filters.scss
  web/src/ui/components/Header/Header.js
  web/src/ui/pages/Home/Home.js
Labels: 🔍 Ready for Review

#226 build(vcs): add vscode settings folder to gitignore
  .gitignore
Labels: 🔍 Ready for Review

#227 build(vcs): dummy pr
  web/tools/assetsTransformer.js
Labels: 🔍 Ready for Review

#228 fix(front): show build ID rather than mr ID in artifact title
  web/src/ui/components/Build/ArtifactCard.js
  web/src/ui/components/Build/BuildAndMergeRequest.js
Labels: 🔍 Ready for Review

#230 feat(front): make build blocks more compact
  web/src/assets/main.scss
  web/src/ui/components/Build/Build.scss
  web/src/ui/components/Build/BuildContainer.js
Labels: 🔍 Ready for Review

#231 feat(web): add linebreaks to build messages
  web/package.json
  web/src/ui/components/Build/Build.scss
  web/src/ui/components/Build/BuildAndMergeRequest.js
Labels: 🔍 Ready for Review

#233 feat(web): redirect to /404
  web/src/App.js
  web/src/ui/components/Header/Header.js
  web/src/ui/pages/Error404.js
  web/src/ui/pages/Home/Home.js
Labels: 🔍 Ready for Review

#238 fix(front): enable all filter interactivity in modal
  web/.eslintrc.json
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/FilterModal/FilterModal.scss
Labels: 🔍 Ready for Review

#241 feat(front): add sharable links to builds and artifacts in feed
  web/.eslintrc.json
  web/src/ui/components/AnchorLink.js
  web/src/ui/components/Build/ArtifactCard.js
  web/src/ui/components/Build/Build.scss
  web/src/ui/components/Build/BuildAndMergeRequest.js
Labels: 🔍 Ready for Review

#242 feat(front): add state tags to collapsed build blocks
  web/src/api/dataTransforms.js
  web/src/assets/main.scss
  web/src/constants/index.js
  web/src/ui/Tag/Tag.js
  web/src/ui/Tag/Tag.scss
  web/src/ui/components/AnchorLink.js
  web/src/ui/components/AnchorLink.scss
  web/src/ui/components/Build/ArtifactActionButton.js
  web/src/ui/components/Build/ArtifactCard.js
  web/src/ui/components/Build/Build.scss
  web/src/ui/components/Build/BuildAndMergeRequest.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/Build/CardHeader.js
  web/src/ui/styleTools/brandIcons.js
  web/src/ui/styleTools/buttonStyler.js
Labels: 🔍 Ready for Review

#243 refactor(front): minor refactor, plus bugfix for gombile filter selector
  web/src/ui/components/AnchorLink/AnchorLink.js
  web/src/ui/components/AnchorLink/AnchorLink.scss
  web/src/ui/components/Build/ArtifactCard.js
  web/src/ui/components/Build/BuildAndMergeRequest.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/FilterModal/FilterModal.scss
Labels: 🔍 Ready for Review

#244 build(front): use css modules and some webpack cleanup
  web/package-lock.json
  web/package.json
  web/src/ui/components/AnchorLink/AnchorLink.js
  web/src/ui/components/AnchorLink/AnchorLink.module.scss
  web/webpack.config.common.js
  web/webpack.config.dev.js
  web/webpack.config.prod.js
Labels: 🔍 Ready for Review

#246 fix: support artifact_kinds and build_id filters together
  go/pkg/yolosvc/api_buildlist.go
Labels: 🔍 Ready for Review

#247 refactor(front): memoize build grouping and split out build components
  web/src/store/ResultStore.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/BuildListContainer.js
  web/src/ui/pages/Home/Home.js
Labels: 🔍 Ready for Review

#217 feat: filter by branch
  api/yolopb.proto
  go/gen.sum
  go/pkg/yolopb/yolopb.pb.go
  go/pkg/yolosvc/api_buildlist.go
  go/pkg/yolosvc/api_buildlistfilters.go
Labels: 🔍 Ready for Review

#248 refactor(front): simplify some code in ./web
  web/.eslintrc.json
  web/package.json
  web/src/api/dataTransforms.js
  web/src/store/ResultStore.js
  web/src/ui/components/AnchorLink/AnchorLink.js
  web/src/ui/components/Build/ArtifactCard.js
  web/src/ui/components/Build/BuildAndMergeRequest.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/Build/CardHeader.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/BuildListContainer.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/pages/Home/Home.js
  web/src/util/getters.js
Labels: 🔍 Ready for Review

#260 feat(front): add build driver filter to filterUI
  web/.eslintrc.json
  web/src/constants/index.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/Filters/Filters.js
  web/src/ui/components/Filters/Filters.scss
Labels: front, 🔍 Ready for Review

#249 feat(web): add build feed date divider
  web/src/api/dataGetters.js
  web/src/api/dataTransforms.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/Divider.js
  web/src/ui/components/Divider.module.scss
  web/src/util/date.js
Labels: 🔍 Ready for Review

#267 fix(front): fix small and annoying lack of spacing in mr status tag
  web/src/ui/components/Build/BuildAndMergeRequest.js
Labels: 🔍 Ready for Review

#268 feat(front): show build.short_id or build.id in each build section
  web/src/ui/components/Author/Author.js
  web/src/ui/components/Author/Author.module.scss
  web/src/ui/components/Build/ArtifactRow.js
  web/src/ui/components/Build/Build.scss
  web/src/ui/components/Build/BuildAndMrContainer.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/Build/CardHeader.js
  web/src/util/getters.js
Labels: 🔍 Ready for Review

#269 feat(front): show artifacts if 1st or build branch is master
  web/src/ui/components/Build/BuildAndMrContainer.js
  web/src/ui/components/Build/BuildContainer.js
Labels: 🔍 Ready for Review

#270 feat: artifact caching
  .gitignore
  go/Makefile
  go/cmd/yolo/main.go
  go/gen.sum
  go/pkg/bintray/bintray.go
  go/pkg/yolosvc/api_download.go
  go/pkg/yolosvc/service.go
  go/pkg/yolosvc/util.go
Labels: 🔍 Ready for Review

#271 chore: update yolo.berty.io deployment configuration
  deployments/yolo.berty.io/Makefile
  deployments/yolo.berty.io/docker-compose.yml
Labels: 🔍 Ready for Review

#273 chore: small markdown improvements
  README.md
Labels: 🔍 Ready for Review

#275 Fix(front): add spaces before build ID in block title
  web/src/ui/components/Build/CardTitle.js
Labels: 🔍 Ready for Review

#276 feat(web): generate QR code for direct install
  web/.eslintrc.json
  web/package-lock.json
  web/package.json
  web/src/assets/main.scss
  web/src/ui/components/Build/ArtifactActionButton.js
  web/src/ui/components/Build/ArtifactRow.js
  web/src/ui/components/Build/Build.scss
  web/src/ui/components/MessageModal/MessageModal.js
  web/src/ui/components/ProtocolDisclaimer.js
  web/src/ui/components/QRCodeModal.js
  web/src/ui/pages/Home/Home.js
  web/src/ui/styleTools/buttonStyler.js
Labels: ✅ Approved

#277 fix(front): buildlist crashing when no artifacts
  web/src/ui/components/Build/BuildAndMrContainer.js
Labels: 🔍 Ready for Review

#279 feat(front): Add auto-refresh feature to UI
  web/src/api/mock.js
  web/src/store/ResultStore.js
  web/src/ui/components/BuildListContainer.js
  web/src/ui/components/Filters/Filters.js
  web/src/ui/components/Header/Header.js
  web/src/ui/components/Spinner.js
  web/src/ui/components/Spinner.module.scss
  web/src/ui/pages/Home/Home.js
Labels: 🔍 Ready for Review

#282 refactor(front): harmonize vocabulary
  web/src/ui/components/Build/ArtifactRow.js
  web/src/ui/components/Build/Build.scss
  web/src/ui/components/Build/BuildAndMrContainer.js
  web/src/ui/components/Build/BuildBlockHeader.js
  web/src/ui/components/Build/BuildBlockTitle.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/Build/CardHeader.js
  web/src/ui/components/Build/CardTitle.js
Labels: 🔍 Ready for Review

#283 fix(front): chevron and author overlap on small screens
  web/src/ui/components/Author/Author.module.scss
  web/src/ui/components/Build/BuildBlockHeader.js
Labels: 🔍 Ready for Review

#287 feat(front): add build state UI filter
  web/.eslintrc.json
  web/package.json
  web/src/constants/index.js
  web/src/store/ResultStore.js
  web/src/ui/components/ActionWidgets.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/Filters/Filters.js
  web/src/ui/components/Filters/Filters.scss
  web/src/ui/components/Header/Header.js
  web/src/ui/pages/Home/Home.js
  web/src/util/getters.js
Labels: 🔍 Ready for Review

#289 feat: add 'Merged' state for PRs
  api/yolopb.proto
  go/gen.sum
  go/pkg/yolopb/yolopb.pb.go
  go/pkg/yolosvc/driver_github.go
  web/src/constants/index.js
Labels: 🔍 Ready for Review

#290 feat(front): show running build count in collapsed blocks
  web/src/api/dataGetters.js
  web/src/api/dataTransforms.js
  web/src/ui/components/Build/BuildAndMrContainer.js
  web/src/ui/components/Build/BuildBlockHeader.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/BuildList.js
  web/src/util/getters.js
Labels: 🔍 Ready for Review

#291 feat: detect if a PR is W-I-P or Draft
  api/yolopb.proto
  go/gen.sum
  go/pkg/yolopb/yolopb.pb.go
  go/pkg/yolosvc/driver_github.go
Labels: 🔍 Ready for Review

#293 feat: download stats
  api/yolopb.proto
  go/gen.sum
  go/pkg/yolopb/model.go
  go/pkg/yolopb/yolopb.pb.go
  go/pkg/yolosvc/api_buildlist.go
  go/pkg/yolosvc/api_dev.go
  go/pkg/yolosvc/api_download.go
Labels: 🔍 Ready for Review

#295 feat(front): detect and set init artifact kind filters per useragent
  web/src/constants/index.js
  web/src/store/ResultStore.js
  web/src/ui/pages/Home/Home.js
  web/src/util/browser.js
Labels: 🔍 Ready for Review

#292 feat(front): build block header icons correspond to MR status
  web/src/ui/components/Build/ArtifactRow.js
  web/src/ui/components/Build/BuildBlockHeader.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/styleTools/themes.js
Labels: 🔍 Ready for Review

#297 refactor(front): add inline theme styles to HOCs
  web/src/constants/index.js
  web/src/ui/components/AnchorLink/AnchorLink.js
  web/src/ui/components/ApiKeyPrompt.js
  web/src/ui/components/Author/Author.js
  web/src/ui/components/Build/BuildBlockTitle.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/BuildListContainer.js
  web/src/ui/components/Divider/Divider.js
  web/src/ui/components/Divider/Divider.module.scss
  web/src/ui/components/ErrorDisplay/ErrorDisplay.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/FilterModal/FilterModal.scss
  web/src/ui/components/Filters/Filters.js
  web/src/ui/components/Header/Header.js
  web/src/ui/components/Header/Header.scss
  web/src/ui/components/OutlineWidget/OutlineWidget.js
  web/src/ui/components/OutlineWidget/OutlineWidget.module.scss
  web/src/ui/components/ShowFiltersButton.js
  web/src/ui/components/ShownBuildsButton.js
  web/src/ui/components/Spinner.js
  web/src/ui/components/Spinner/Spinner.js
  web/src/ui/components/Spinner/Spinner.module.scss
  web/src/ui/components/Tag/Tag.js
  web/src/ui/components/ThemeToggler.js
  web/src/ui/helpers/withButtonStyles.js
  web/src/ui/helpers/withTheme.js
  web/src/ui/helpers/withWidgetStyles.js
  web/src/ui/pages/Error404.js
  web/src/ui/pages/Home/Home.js
  web/src/ui/styleTools/buttonStyler.js
  web/src/ui/styleTools/projectIcons.js
  web/src/ui/styleTools/vcsIcons.js
  web/src/ui/styleTools/widgetStyles.js
  web/src/util/getters.js
Labels: 🔍 Ready for Review

#300 refactor(front): move things and comment others
  web/src/App.js
  web/src/api/apiResponseGetters.js
  web/src/api/apiResponseTransforms.js
  web/src/api/cookies.js
  web/src/api/index.js
  web/src/api/mock.js
  web/src/api/requests.js
  web/src/assets/main.scss
  web/src/store/ResultStore.js
  web/src/ui/components/ApiKeyPrompt.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/BuildList.js
  web/src/ui/components/FilterModal/FilterModal.js
  web/src/ui/components/Filters/Filters.js
  web/src/ui/components/Header/Header.js
  web/src/ui/pages/Error404/Error404.js
  web/src/ui/pages/Home/Home.js
  web/src/util/getters.js
Labels: 🔍 Ready for Review

#303 feat(front): request 25 builds if no UI filters are in place
  web/src/constants/index.js
  web/src/ui/pages/Home/Home.js
Labels: 🔍 Ready for Review

#310 fix(front): apiKey input field encoding
  web/src/ui/components/ApiKeyPrompt.js
Labels: 🔍 Ready for Review

#311 chore: increase default cookie expiration
  web/src/api/cookies.js
Labels: 🔍 Ready for Review

#313 fix(front): set initial theme
  web/src/App.js
  web/src/assets/_variables.scss
  web/src/assets/main.scss
  web/src/ui/components/ThemeToggler.js
Labels: 🔍 Ready for Review

#314 fix(front): fix hiding latest build when showing all builds
  web/src/ui/components/Build/BuildContainer.js
Labels: 🔍 Ready for Review

#315 fix(front): call buildlist formatters only on api data receipt
  web/src/api/apiResponseTransforms.js
  web/src/ui/components/BuildList.js
Labels: 🔍 Ready for Review

#316 feat(front): recolor artifact and download button
  web/src/ui/components/Build/ArtifactActionButton.js
  web/src/ui/components/Build/ArtifactRow.js
  web/src/ui/components/Build/Build.scss
  web/src/ui/components/Build/BuildAndMrContainer.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/Tag/Tag.js
  web/src/ui/styleTools/buttonStyler.js
Labels: 🔍 Ready for Review

#317 chore: configure github actions
  .github/workflows/ci.yml
  go/pkg/yolosvc/api_buildlist.go
  go/pkg/yolosvc/api_buildlistfilters.go
  go/pkg/yolosvc/api_dev.go
  go/pkg/yolosvc/api_ping.go
  go/pkg/yolosvc/api_plist.go
  go/pkg/yolosvc/api_status.go
  go/pkg/yolosvc/driver_github.go
  go/pkg/yolosvc/server.go
Labels: 🔍 Ready for Review

#318 refactor(front): split out build-block related subcomponents
  web/src/ui/components/Author/Author.js
  web/src/ui/components/Build/ArtifactRow.js
  web/src/ui/components/Build/Build.scss
  web/src/ui/components/Build/BuildAndMrContainer.js
  web/src/ui/components/Build/BuildAndMrContainerWidgets.js
  web/src/ui/components/Build/BuildBlockHeader.js
  web/src/ui/components/Build/BuildContainer.js
  web/src/ui/components/Build/BuildMessage.js
  web/src/ui/components/ConditionallyWrappedComponent.js
  web/src/ui/components/ShowingOlderBuildsTag.js
  web/src/ui/styleTools/buttonStyler.js
  web/src/ui/styleTools/themes.js
Labels: 🔍 Ready for Review
